# Generated by Django 5.0.6 on 2024-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facultades',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('id_decano', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'EventsDB_facultades',
            },
        ),
    ]
