# Generated by Django 5.0.6 on 2024-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_facultad', models.IntegerField()),
                ('id_coordinador', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_dpto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_pais', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('tipo_contratacion', models.CharField(max_length=30)),
                ('tipo_empleado', models.CharField(max_length=30)),
                ('cod_facultad', models.IntegerField()),
                ('codigo_sede', models.IntegerField()),
                ('lugar_nacimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=15)),
                ('nro_telefono', models.CharField(max_length=15)),
                ('id_decano', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('codigo_area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('cod_ciudad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoContratacion',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
